name: CI

on:
    push:

jobs:
    lint:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: ./.github/workflows/node
            - run: npm run lint
